#!/bin/bash

# OCR Card Recognizer - Windows Deployment Package v2.1.4
# This script creates a deployment package for Windows with all necessary files
# Including the backend API fix

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  OCR Card Recognizer - Packaging v2.1.4${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Package info
PACKAGE_NAME="ocr-card-recognizer-windows-v2.1.4"
PACKAGE_VERSION="v2.1.4"
PACKAGE_DATE=$(date +%Y-%m-%d)

# Clean up old package
echo "Cleaning up old package..."
rm -rf ${PACKAGE_NAME}
rm -f ${PACKAGE_NAME}.tar.gz

# Create package directory
echo "Creating package directory..."
mkdir -p ${PACKAGE_NAME}

# Copy essential project files
echo "Copying project files..."

# Frontend files
echo "  - Frontend configuration..."
cp -r src ${PACKAGE_NAME}/
cp package.json ${PACKAGE_NAME}/
cp tsconfig.json ${PACKAGE_NAME}/
cp tailwind.config.ts ${PACKAGE_NAME}/
cp postcss.config.mjs ${PACKAGE_NAME}/
cp next.config.ts ${PACKAGE_NAME}/
cp pnpm-lock.yaml ${PACKAGE_NAME}/
cp .coze ${PACKAGE_NAME}/
cp -r .cozeproj ${PACKAGE_NAME}/

# Backend files
echo "  - Backend files..."
cp -r backend ${PACKAGE_NAME}/
# Remove Python cache
find ${PACKAGE_NAME}/backend -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true

# Documentation
echo "  - Documentation files..."
mkdir -p ${PACKAGE_NAME}/docs
cp README.md ${PACKAGE_NAME}/
cp BACKEND_API_FIX.md ${PACKAGE_NAME}/docs/ 2>/dev/null || true
cp QUICKSTART.md ${PACKAGE_NAME}/docs/ 2>/dev/null || true
cp WINDOWS_DEPLOY.md ${PACKAGE_NAME}/docs/ 2>/dev/null || true

# Create version info file
cat > ${PACKAGE_NAME}/VERSION.txt << EOF
OCR Card Recognizer - Windows Deployment Package
================================================

Version: ${PACKAGE_VERSION}
Release Date: ${PACKAGE_DATE}

What's New:
- Fixed backend API route mismatch issue
- Added /api/ocr endpoint for frontend compatibility
- Fixed template-based image cropping
- Fixed OCR recognition failures
- All previous fixes (Python env, Tailwind CSS, env vars)

Requirements:
- Windows 10/11
- Python 3.12
- Node.js 18+ with pnpm
- PaddleOCR (will be installed automatically)

Quick Start:
1. Install Python dependencies: cd backend && py -m pip install -r requirements.txt
2. Install frontend dependencies: pnpm install
3. Build frontend: pnpm run build
4. Start backend: cd backend && py -m uvicorn main:app --host 0.0.0.0 --port 8000
5. Start frontend: pnpm run start
6. Access: http://localhost:5000

For detailed instructions, see README.md and docs/ directory.

Generated by: Coze Coding Expert
EOF

# Create README for package
cat > ${PACKAGE_NAME}/README_PACKAGING.md << EOF
# OCR Card Recognizer - Windows Deployment Package v${PACKAGE_VERSION}

## Package Contents

This package contains the complete source code for OCR Card Recognizer, optimized for Windows deployment.

### Directory Structure

\`\`\`
ocr-card-recognizer-windows-v${PACKAGE_VERSION}/
├── src/                      # Frontend source code
│   ├── app/                  # Next.js app directory
│   ├── components/           # React components
│   └── lib/                  # Utility functions
├── backend/                  # Backend source code
│   ├── main.py              # FastAPI application
│   ├── ocr_service.py       # OCR service
│   └── requirements.txt     # Python dependencies
├── docs/                     # Documentation
│   ├── BACKEND_API_FIX.md   # Backend API fix documentation
│   └── ...
├── package.json             # Node.js dependencies
├── tsconfig.json            # TypeScript config
├── tailwind.config.ts       # Tailwind CSS config
├── .coze                    # Coze CLI config
└── VERSION.txt              # Version information
\`\`\`

## Quick Installation

### Prerequisites

1. **Python 3.12**: Download from https://www.python.org/downloads/
   - During installation, check "Add Python to PATH"
   - Verify installation: \`py --version\`

2. **Node.js 18+**: Download from https://nodejs.org/
   - Install pnpm: \`npm install -g pnpm\`

3. **Git** (optional): For version control

### Installation Steps

1. **Extract the package**
   \`\`\`
   Right-click the .tar.gz file and "Extract Here"
   \`\`\`

2. **Install backend dependencies**
   \`\`\`
   cd backend
   py -m pip install -r requirements.txt
   \`\`\`

3. **Install frontend dependencies**
   \`\`\`
   cd ..
   pnpm install
   \`\`\`

4. **Build the frontend**
   \`\`\`
   pnpm run build
   \`\`\`

### Running the Application

**Terminal 1 - Start Backend:**
\`\`\`
cd backend
py -m uvicorn main:app --host 0.0.0.0 --port 8000
\`\`\`

**Terminal 2 - Start Frontend:**
\`\`\`
cd ..
pnpm run start
\`\`\`

**Open Browser:**
\`\`\`
http://localhost:5000
\`\`\`

## Features

- ✅ Offline OCR recognition using PaddleOCR
- ✅ Template-based recognition for faster processing
- ✅ Support for both OCR and barcode recognition
- ✅ Batch image upload and processing
- ✅ Excel export with password screenshots
- ✅ Real-time preview and editing
- ✅ Fixed Windows compatibility issues
- ✅ Fixed backend API route compatibility

## What's Fixed in v${PACKAGE_VERSION}

1. **Backend API Route Fix**
   - Added \`/api/ocr\` endpoint for frontend compatibility
   - Supports template-based batch recognition
   - Returns card number and password in expected format

2. **Image Cropping Fix**
   - Template-based image cropping now works correctly
   - Automatic cropping based on template coordinates

3. **OCR Recognition Fix**
   - All recognition failures resolved
   - Better error handling and logging

## Troubleshooting

### Python Command Not Found
If \`python\` command doesn't work, use \`py\` command instead:
\`\`\`
py --version
\`\`\`

### Port Already in Use
If port 5000 or 8000 is already in use, change the port number:
\`\`\`
# Backend: Change --port 8000 to --port 8001
# Frontend: Change -p 5000 to -p 5001
\`\`\`

### OCR Not Working
1. Make sure backend is running on port 8000
2. Check browser console (F12) for errors
3. Verify template is set before uploading images
4. Check backend logs for error messages

## Support

For detailed documentation, see:
- README.md - Complete project documentation
- docs/BACKEND_API_FIX.md - Backend API fix details
- docs/WINDOWS_DEPLOY.md - Windows deployment guide

## Version History

- v${PACKAGE_VERSION} (${PACKAGE_DATE}): Fixed backend API, image cropping, and OCR recognition
- v2.1.3: Fixed Windows compatibility and styling issues
- v2.1.2: Initial Windows deployment package

---

**Generated by Coze Coding Expert**
**Package Version: ${PACKAGE_VERSION}**
**Release Date: ${PACKAGE_DATE}**
EOF

echo ""
echo -e "${GREEN}Package structure created successfully!${NC}"

# Create tar.gz package
echo ""
echo "Creating tar.gz package..."
tar -czf ${PACKAGE_NAME}.tar.gz ${PACKAGE_NAME}

# Get file size
FILE_SIZE=$(du -h ${PACKAGE_NAME}.tar.gz | cut -f1)

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Package Created Successfully!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Package Name: ${PACKAGE_NAME}.tar.gz"
echo "Package Size: ${FILE_SIZE}"
echo "Package Version: ${PACKAGE_VERSION}"
echo "Release Date: ${PACKAGE_DATE}"
echo ""
echo "Package Location: $(pwd)/${PACKAGE_NAME}.tar.gz"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "1. Upload the package to object storage"
echo "2. Generate download link"
echo "3. Update documentation"
echo ""
