#!/bin/bash

# OCR Card Recognizer - Windows Deployment Package v2.1.5
# This script creates a deployment package for Windows with all necessary files
# Including PaddlePaddle/PaddleOCR version compatibility fix

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  OCR Card Recognizer - Packaging v2.1.5${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Package info
PACKAGE_NAME="ocr-card-recognizer-windows-v2.1.5"
PACKAGE_VERSION="v2.1.5"
PACKAGE_DATE=$(date +%Y-%m-%d)

# Clean up old package
echo "Cleaning up old package..."
rm -rf ${PACKAGE_NAME}
rm -f ${PACKAGE_NAME}.tar.gz

# Create package directory
echo "Creating package directory..."
mkdir -p ${PACKAGE_NAME}

# Copy essential project files
echo "Copying project files..."

# Frontend files
echo "  - Frontend configuration..."
cp -r src ${PACKAGE_NAME}/
cp package.json ${PACKAGE_NAME}/
cp tsconfig.json ${PACKAGE_NAME}/
cp tailwind.config.ts ${PACKAGE_NAME}/
cp postcss.config.mjs ${PACKAGE_NAME}/
cp next.config.ts ${PACKAGE_NAME}/
cp pnpm-lock.yaml ${PACKAGE_NAME}/
cp .coze ${PACKAGE_NAME}/
cp -r .cozeproj ${PACKAGE_NAME}/

# Backend files
echo "  - Backend files..."
cp -r backend ${PACKAGE_NAME}/
# Remove Python cache
find ${PACKAGE_NAME}/backend -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true

# Documentation
echo "  - Documentation files..."
mkdir -p ${PACKAGE_NAME}/docs
cp README.md ${PACKAGE_NAME}/
cp QUICKSTART.md ${PACKAGE_NAME}/docs/ 2>/dev/null || true
cp QUICKSTART_v2.1.5.md ${PACKAGE_NAME}/docs/ 2>/dev/null || true
cp CHANGELOG_v2.1.5.md ${PACKAGE_NAME}/docs/ 2>/dev/null || true
cp WINDOWS_DEPLOY.md ${PACKAGE_NAME}/docs/ 2>/dev/null || true

# Create version info file
cat > ${PACKAGE_NAME}/VERSION.txt << EOF
OCR Card Recognizer - Windows Deployment Package
================================================

Version: ${PACKAGE_VERSION}
Release Date: ${PACKAGE_DATE}

What's New (v2.1.5):
- Fixed PaddlePaddle version compatibility (downgraded to 2.6.2)
- Fixed PaddleOCR version compatibility (downgraded to 2.8.0)
- Added install.bat script for easy dependency installation
- Added start-backend-fixed.bat script with oneDNN disabled
- Fixed frontend API port configuration (8000)
- Updated documentation with version compatibility guide
- All previous fixes (Python env, Tailwind CSS, env vars, API routes)

Critical Changes:
- PaddlePaddle: 2.6.2 (REQUIRED for Windows stability)
- PaddleOCR: 2.8.0 (REQUIRED for compatibility)
- Do NOT use PaddlePaddle 3.x or PaddleOCR 3.4.0 on Windows

Requirements:
- Windows 10/11
- Python 3.12
- Node.js 18+ with pnpm
- PaddleOCR 2.8.0 (will be installed automatically)

Quick Start:
1. Install Python dependencies: cd backend && install.bat
2. Install frontend dependencies: pnpm install
3. Build frontend: pnpm run build
4. Start backend: cd backend && start-backend-fixed.bat
5. Start frontend: pnpm run start
6. Access: http://localhost:5000

For detailed instructions, see README.md and docs/ directory.

Generated by: Coze Coding Expert
EOF

# Create README for package
cat > ${PACKAGE_NAME}/README_PACKAGING.md << EOF
# OCR Card Recognizer - Windows Deployment Package v${PACKAGE_VERSION}

## Package Contents

This package contains the complete source code for OCR Card Recognizer, optimized for Windows deployment.

### Directory Structure

\`\`\`
ocr-card-recognizer-windows-v${PACKAGE_VERSION}/
├── src/                      # Frontend source code
│   ├── app/                  # Next.js app directory
│   ├── components/           # React components
│   └── lib/                  # Utility functions
├── backend/                  # Backend source code
│   ├── main.py              # FastAPI application
│   ├── ocr_service.py       # OCR service
│   ├── install.bat          # Installation script
│   ├── start-backend-fixed.bat  # Startup script
│   └── requirements.txt     # Python dependencies
├── docs/                     # Documentation
│   ├── QUICKSTART_v2.1.5.md # Quick start guide
│   └── CHANGELOG_v2.1.5.md  # Update changelog
├── package.json             # Node.js dependencies
├── tsconfig.json            # TypeScript config
├── tailwind.config.ts       # Tailwind CSS config
├── .coze                    # Coze CLI config
└── VERSION.txt              # Version information
\`\`\`

## Quick Installation

### Prerequisites

1. **Python 3.12**: Download from https://www.python.org/downloads/
   - During installation, check "Add Python to PATH"
   - Verify installation: \`py --version\`

2. **Node.js 18+**: Download from https://nodejs.org/
   - Install pnpm: \`npm install -g pnpm\`

### Installation Steps

1. **Extract the package**
   \`\`\`
   Right-click the .tar.gz file and "Extract Here"
   \`\`\`

2. **Install backend dependencies**
   \`\`\`
   cd backend
   install.bat
   \`\`\`

3. **Install frontend dependencies**
   \`\`\`
   cd ..
   pnpm install
   \`\`\`

4. **Build the frontend**
   \`\`\`
   pnpm run build
   \`\`\`

### Running the Application

**Terminal 1 - Start Backend:**
\`\`\`
cd backend
start-backend-fixed.bat
\`\`\`

**Terminal 2 - Start Frontend:**
\`\`\`
cd ..
pnpm run start
\`\`\`

**Open Browser:**
\`\`\`
http://localhost:5000
\`\`\`

## Features

- ✅ Offline OCR recognition using PaddleOCR
- ✅ Template-based recognition for faster processing
- ✅ Support for both OCR and barcode recognition
- ✅ Batch image upload and processing
- ✅ Excel export with password screenshots
- ✅ Real-time preview and editing
- ✅ Fixed Windows compatibility issues
- ✅ Fixed PaddlePaddle/PaddleOCR version compatibility
- ✅ Fixed backend API route compatibility

## What's Fixed in v${PACKAGE_VERSION}

### Critical Version Compatibility Fix

**Problem**: PaddlePaddle 3.x and PaddleOCR 3.4.0 had severe compatibility issues on Windows
- oneDNN errors causing OCR recognition failures
- API incompatibility between versions

**Solution**: Downgraded to stable version combination
- PaddlePaddle: 3.3.0 → **2.6.2**
- PaddleOCR: 3.4.0 → **2.8.0**

### New Scripts

1. **install.bat**
   - Automated dependency installation
   - Version checking and validation
   - Error handling and user-friendly messages

2. **start-backend-fixed.bat**
   - Disables oneDNN features to prevent errors
   - Sets required environment variables
   - Provides detailed startup logs

### Frontend API Port Fix

- Changed default port from 8001 to 8000
- Now correctly connects to backend service

### Documentation Updates

- QUICKSTART_v2.1.5.md: Complete installation guide
- CHANGELOG_v2.1.5.md: Detailed changelog
- Version compatibility matrix
- Troubleshooting guide

## Version Compatibility

### Windows Platform (Recommended)

| Component | Version | Status |
|-----------|---------|--------|
| Python | 3.12 | ✅ Tested |
| PaddlePaddle | 2.6.2 | ✅ Stable |
| PaddleOCR | 2.8.0 | ✅ Stable |
| Node.js | 18+ | ✅ Tested |
| Windows | 10/11 | ✅ Tested |

### Known Incompatible Combinations

| PaddlePaddle | PaddleOCR | Status |
|--------------|-----------|--------|
| 3.3.0 | 3.4.0 | ❌ oneDNN errors |
| 3.x | 2.8.0 | ❌ API incompatible |
| 2.6.2 | 3.4.0 | ❌ set_optimization_level |

## Troubleshooting

### OCR Recognition Fails

**Symptom**: \`ERROR: ConvertPirAttribute2RuntimeAttribute not support\`

**Solution**:
1. Check versions:
   \`\`\`
   py -c "import paddle; print(f'PaddlePaddle: {paddle.__version__}')"
   py -c "import paddleocr; print(f'PaddleOCR: {paddleocr.__version__}')"
   \`\`\`
2. Ensure versions are 2.6.2 and 2.8.0
3. Reinstall if needed:
   \`\`\`
   py -m pip uninstall paddlepaddle paddleocr -y
   py -m pip install "paddlepaddle==2.6.2"
   py -m pip install "paddleocr==2.8.0"
   \`\`\`
4. Use \`start-backend-fixed.bat\` to start backend

### Installation Fails

**Symptom**: \`ERROR: Failed to install dependencies\`

**Solution**:
1. Use \`install.bat\` script:
   \`\`\`
   cd backend
   install.bat
   \`\`\`
2. Or manually install:
   \`\`\`
   py -m pip install -r requirements.txt
   \`\`\`

## Performance Tips

- Use batch recognition for multiple images
- Keep backend service running to avoid reinitialization
- Disable oneDNN may slightly reduce performance (~10-20%)
- Consider GPU acceleration if needed (requires PaddlePaddle-GPU)

## Support

For issues and questions, refer to:
- README.md: Main documentation
- docs/QUICKSTART_v2.1.5.md: Quick start guide
- docs/CHANGELOG_v2.1.5.md: Detailed changelog

## License

See LICENSE file for details.

---
Version: ${PACKAGE_VERSION}
Release Date: ${PACKAGE_DATE}
Generated by: Coze Coding Expert
EOF

# Create package info JSON
cat > ${PACKAGE_NAME}/package-info.json << EOF
{
  "name": "ocr-card-recognizer",
  "version": "${PACKAGE_VERSION}",
  "platform": "windows",
  "releaseDate": "${PACKAGE_DATE}",
  "requirements": {
    "python": "3.12",
    "nodejs": "18+",
    "paddlepaddle": "2.6.2",
    "paddleocr": "2.8.0",
    "pnpm": "8+"
  },
  "features": [
    "Offline OCR recognition",
    "Template-based recognition",
    "Barcode recognition",
    "Batch processing",
    "Excel export",
    "Real-time preview"
  ],
  "fixes": [
    "PaddlePaddle version compatibility",
    "PaddleOCR version compatibility",
    "Windows oneDNN errors",
    "API route mismatch",
    "Installation scripts"
  ],
  "quickStart": {
    "backend": "cd backend && install.bat",
    "frontend": "pnpm install && pnpm run build",
    "run": "cd backend && start-backend-fixed.bat && pnpm run start"
  }
}
EOF

# Create tar.gz package
echo ""
echo "Creating tar.gz package..."
tar -czf ${PACKAGE_NAME}.tar.gz ${PACKAGE_NAME}

# Get package size
PACKAGE_SIZE=$(du -h ${PACKAGE_NAME}.tar.gz | cut -f1)

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Packaging Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Package: ${PACKAGE_NAME}.tar.gz"
echo "Size: ${PACKAGE_SIZE}"
echo "Version: ${PACKAGE_VERSION}"
echo "Date: ${PACKAGE_DATE}"
echo ""
echo "Files included:"
ls -lh ${PACKAGE_NAME}/
echo ""
echo -e "${YELLOW}Next step: Upload to object storage${NC}"
echo "Run: node scripts/upload-package-v2.1.5.js"
